services:
  kms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:443"
    volumes:
      - .:/data/app/kms
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
