# Generated by Django 4.0.6 on 2023-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0002_auto_20210819_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
